<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = "products";

    protected $fillable = [
        "id",
        "type_id",
        "sku",
        "opera_sku",
        "old_sku",
        "override_opera",
        "name",
        "inlet",
        "outlet",
        "hose_type",
        "angle_in_deg",
        "max_lpm",
        "voltage",
        "material",
        "bar",
        "o-ring_thickness",
        "diameter",
        "colour",
        "rpm",
        "status",
        "url_key",
        "visibility",
        "clearance",
        "max_temperature",
        "description",
        "short_description",
        "tech_spec_1",
        "tech_spec_2",
        "tech_spec_3",
        "product_videos",
        "nozzle_value",
        "nozzle_size",
        "foam_value",
        "is_featured",
        "featured_position",
        "hose_clamp_size",
        "orifice_size",
        "shoe_size",
        "thread",
        "size_and_angle",
        "inlet_outlet",
        "clothing_size",
        "wheel_style",
        "flow_and_pressure",
        "country_of_manufacture",
        "select_nozzle_size",
        "dn_internal_diameter",
        "currency",
        "pack_size",
        "easyturn",
        "priority",
        "manufacturer_number_1",
        "manufacturer_number_2",
        "manufacturer_number_3",
        "manufacturer_number_4",
        "manufacturer_number_5",
        "manufacturer_number_6",
        "manufacturer_number_7",
        "manufacturer_number_8",
        "manufacturer_number_9",
        "manufacturer_number_10",
        "hose_application",
        "hose_inlet",
        "hose_outlet",
        "hose_length",
        "hose_colour",
        "price",
        "special_price",
        "poa",
        "poa_price",
        "msrp",
        "meta_title",
        "meta_keywords",
        "meta_description",
        "pdf_title_1",
        "pdf_title_2",
        "pdf_title_3",
        "pdf_title_4",
        "bullet_point_1",
        "bullet_point_2",
        "bullet_point_3",
        "bullet_point_4",
        "maintenance_videos",
        "maintenance_video_title_1",
        "maintenance_video_url_1",
        "maintenance_video_title_2",
        "maintenance_video_url_2",
        "maintenance_video_url_3",
        "maintenance_video_title_3",
        "maintenance_video_title_4",
        "maintenance_video_url_4",
        "stock_status",
        "related_products",
        "configurable_product_parent_id",
    ];

    public function categories()
    {
        return $this->hasManyThrough(Category::class, ProductCategory::class,
            "product_id", "id", "id", "category_id");
    }
}
